### ISSUE TITLE
API 작성

### ISSUE THREAD

**Issue by yjjjwww** [codestates/BEB-05-Beginners#6]
### ISSUE
-필요한 기능에 따라 필요한 파라미터, 요청 형식, 응답 형식을 포함한 API를 작성한다.

### TODO
1. [x] 회원가입 API
2. [ ] 글 작성 시 보상토큰을 지급받는 API
3. [ ] 유저간 토큰을 전송하는 API
4. [x] 특정 유저 정보를 가져오는 API
5. [ ] ETH Faucet을 지급 받는 API
6. [ ] NFT 구매를 위한 API
7. [x] 로그인 API
8. [x] 게시판 GET API
9. [x] 게시글 조회 GET API
