### ISSUE TITLE
데이터베이스 설계

### ISSUE THREAD

**Issue by yjjjwww** [codestates/BEB-05-Beginners#7]
### ISSUE
-데이터베이스 설계하고 schema.sql 파일에 적용합니다.

### TODO
1. [x] 스키마 디자인 작성
2. [x] Schema.sql 파일 작성
3. [x] 각 기능 API에 따른 코드 작성
